version: "3.7"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:3.4
    # volumes:
    #   - ./data:/data/db    
    ports:
      - 27017:27017
      - 28017:28017
    command: mongod --rest --httpinterface
    networks:
      - local
networks:
  local: